/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { User, Course, Enrollment, Activity, PrePostTest, FeedbackAspect, FeedbackComment } from './types';

// Let's create consistent mock users mapping to appropriate entities
export const mockUsers: User[] = [
  {
    id: 'u1',
    name: 'Andi Wijaya',
    email: 'andi.wijaya@company.com',
    division: 'Kitchen',
    area: 'East',
    regional: 'Jatim 1',
    role: 'Sous Chef',
    dateCreated: '2026-05-15',
    lastLogin: '2026-06-10T08:30:00Z',
    status: 'Active',
    learningHours: 24.5,
  },
  {
    id: 'u2',
    name: 'Budi Santoso',
    email: 'budi.santoso@company.com',
    division: 'Service',
    area: 'West',
    regional: 'Jabar 1',
    role: 'Front of House Senior',
    dateCreated: '2026-04-10',
    lastLogin: '2026-06-10T09:15:00Z',
    status: 'Active',
    learningHours: 32.0,
  },
  {
    id: 'u3',
    name: 'Sinta Permata',
    email: 'sinta.permata@company.com',
    division: 'Warehouse',
    area: 'West',
    regional: 'Jabar 2',
    role: 'Logistics Supervisor',
    dateCreated: '2026-05-20',
    lastLogin: '2026-06-09T17:45:00Z',
    status: 'Active',
    learningHours: 12.0,
  },
  {
    id: 'u4',
    name: 'Dedi Kurniawan',
    email: 'dedi.kurniawan@company.com',
    division: 'Management',
    area: 'West',
    regional: 'Jabar 2',
    role: 'Store Manager',
    dateCreated: '2026-01-15',
    lastLogin: '2026-06-10T10:00:00Z',
    status: 'Active',
    learningHours: 45.3,
  },
  {
    id: 'u5',
    name: 'Citra Dewi',
    email: 'citra.dewi@company.com',
    division: 'Kitchen',
    area: 'West',
    regional: 'Jabar 1',
    role: 'Kitchen Helper',
    dateCreated: '2026-06-01',
    lastLogin: '2026-06-08T11:20:00Z',
    status: 'Active',
    learningHours: 8.5,
  },
  {
    id: 'u6',
    name: 'Eko Prasetyo',
    email: 'eko.prasetyo@company.com',
    division: 'Warehouse',
    area: 'East',
    regional: 'Jatim 2',
    role: 'Staff Gudang',
    dateCreated: '2026-05-28',
    lastLogin: '2026-06-07T14:15:00Z', // Gave them a real login timestamp since "user belum pernah login" is deleted
    status: 'Active',
    learningHours: 0,
  },
  {
    id: 'u7',
    name: 'Fani Lestari',
    email: 'fani.lestari@company.com',
    division: 'Service',
    area: 'East',
    regional: 'Jatim 1',
    role: 'Cashier Staff',
    dateCreated: '2026-06-05',
    lastLogin: '2026-06-08T09:30:00Z', // Gave them a real login timestamp since "user belum pernah login" is deleted
    status: 'Active',
    learningHours: 0,
  },
  {
    id: 'u8',
    name: 'Guntur Wibowo',
    email: 'guntur.wibowo@company.com',
    division: 'Kitchen',
    area: 'West',
    regional: 'Jabar 2',
    role: 'Commis Chef',
    dateCreated: '2026-02-12',
    lastLogin: '2026-06-10T07:12:00Z',
    status: 'Active',
    learningHours: 52.1,
  },
  {
    id: 'u9',
    name: 'Hendra Saputra',
    email: 'hendra.saputra@company.com',
    division: 'Service',
    area: 'West',
    regional: 'Jabar 1',
    role: 'Waiter',
    dateCreated: '2026-05-31',
    lastLogin: '2026-06-09T14:22:00Z',
    status: 'Active',
    learningHours: 5.2,
  },
  {
    id: 'u10',
    name: 'Indah Putri',
    email: 'indah.putri@company.com',
    division: 'Management',
    area: 'East',
    regional: 'Jatim 1',
    role: 'Assistant Manager',
    dateCreated: '2026-03-01',
    lastLogin: '2026-06-10T09:40:00Z',
    status: 'Active',
    learningHours: 35.8,
  },
  {
    id: 'u11',
    name: 'Joko Widodo',
    email: 'joko.widodo@company.com',
    division: 'Warehouse',
    area: 'East',
    regional: 'Kalimantan 1',
    role: 'Warehouse Supervisor',
    dateCreated: '2026-06-03',
    lastLogin: '2026-06-06T15:45:00Z', // Gave them a real login timestamp since "user belum pernah login" is deleted
    status: 'Active',
    learningHours: 0,
  },
  {
    id: 'u12',
    name: 'Kiki Amelia',
    email: 'kiki.amelia@company.com',
    division: 'Service',
    area: 'West',
    regional: 'Jabar 2',
    role: 'Hostess',
    dateCreated: '2026-06-06',
    lastLogin: '2026-06-09T10:15:00Z',
    status: 'Active',
    learningHours: 2.1,
  },
  {
    id: 'u13',
    name: 'Lukman Hakim',
    email: 'lukman.hakim@company.com',
    division: 'Kitchen',
    area: 'East',
    regional: 'Jatim 1',
    role: 'Cook Helper',
    dateCreated: '2026-05-10',
    lastLogin: '2026-06-03T11:00:00Z',
    status: 'Active',
    learningHours: 19.8,
  },
  {
    id: 'u14',
    name: 'Mega Utami',
    email: 'mega.utami@company.com',
    division: 'Management',
    area: 'West',
    regional: 'Jabar 1',
    role: 'Supervisor Admin',
    dateCreated: '2026-05-02',
    lastLogin: '2026-06-05T11:15:00Z', // Gave them a real login timestamp since "user belum pernah login" is deleted
    status: 'Active',
    learningHours: 0,
  }
];

export const mockCourses: Course[] = [
  {
    id: 'c1',
    title: 'Food Safety Level 1',
    category: 'Food Safety',
    enrollmentCount: 45,
    completionRate: 96,
    totalAccess: 380,
    lastAccess: '2026-06-10T10:30:00Z',
  },
  {
    id: 'c2',
    title: 'Transformational Leadership',
    category: 'Leadership',
    enrollmentCount: 22,
    completionRate: 82,
    totalAccess: 195,
    lastAccess: '2026-06-10T09:12:00Z',
  },
  {
    id: 'c3',
    title: 'SOP Kitchen & Sanitation',
    category: 'SOP',
    enrollmentCount: 35,
    completionRate: 75,
    totalAccess: 280,
    lastAccess: '2026-06-09T18:00:00Z',
  },
  {
    id: 'c4',
    title: 'Service Excellence Culture',
    category: 'Service Excellence',
    enrollmentCount: 41,
    completionRate: 91,
    totalAccess: 320,
    lastAccess: '2026-06-10T10:15:00Z',
  }
];

export const mockEnrollments: Enrollment[] = [
  // Andi (Kitchen, Malang) - Progress: 90% (In Progress), Quiz: null, Course: c3
  {
    id: 'e1_1',
    userId: 'u1',
    userName: 'Andi Wijaya',
    userDivision: 'Kitchen',
    userArea: 'East',
    userRegional: 'Jatim 1',
    courseId: 'c1',
    courseTitle: 'Food Safety Level 1',
    progress: 100,
    status: 'Completed',
    quizScore: 92,
    learningHours: 8.5,
    deadline: '2026-05-30',
  },
  {
    id: 'e1_2',
    userId: 'u1',
    userName: 'Andi Wijaya',
    userDivision: 'Kitchen',
    userArea: 'East',
    userRegional: 'Jatim 1',
    courseId: 'c3',
    courseTitle: 'SOP Kitchen & Sanitation',
    progress: 90,
    status: 'In Progress',
    quizScore: null,
    learningHours: 11.2,
    deadline: '2026-06-15',
  },
  {
    id: 'e1_3',
    userId: 'u1',
    userName: 'Andi Wijaya',
    userDivision: 'Kitchen',
    userArea: 'East',
    userRegional: 'Jatim 1',
    courseId: 'c2',
    courseTitle: 'Transformational Leadership',
    progress: 40,
    status: 'In Progress',
    quizScore: null,
    learningHours: 4.8,
    deadline: '2026-06-25',
  },

  // Budi (Service, Garut)
  {
    id: 'e2_1',
    userId: 'u2',
    userName: 'Budi Santoso',
    userDivision: 'Service',
    userArea: 'West',
    userRegional: 'Jabar 1',
    courseId: 'c4',
    courseTitle: 'Service Excellence Culture',
    progress: 100,
    status: 'Completed',
    quizScore: 96,
    learningHours: 12.0,
    deadline: '2026-04-15',
  },
  {
    id: 'e2_2',
    userId: 'u2',
    userName: 'Budi Santoso',
    userDivision: 'Service',
    userArea: 'West',
    userRegional: 'Jabar 1',
    courseId: 'c2',
    courseTitle: 'Transformational Leadership',
    progress: 100,
    status: 'Completed',
    quizScore: 94,
    learningHours: 15.2,
    deadline: '2026-05-10',
  },
  {
    id: 'e2_3',
    userId: 'u2',
    userName: 'Budi Santoso',
    userDivision: 'Service',
    userArea: 'West',
    userRegional: 'Jabar 1',
    courseId: 'c1',
    courseTitle: 'Food Safety Level 1',
    progress: 100,
    status: 'Completed',
    quizScore: 98,
    learningHours: 4.8,
    deadline: '2026-05-25',
  },

  // Sinta (Warehouse, Bandung) - Sinta: 25% Overdue
  {
    id: 'e3_1',
    userId: 'u3',
    userName: 'Sinta Permata',
    userDivision: 'Warehouse',
    userArea: 'West',
    userRegional: 'Jabar 2',
    courseId: 'c2',
    courseTitle: 'Transformational Leadership',
    progress: 25,
    status: 'Overdue',
    quizScore: null,
    learningHours: 5.5,
    deadline: '2026-06-05', // Overdue
  },
  {
    id: 'e3_2',
    userId: 'u3',
    userName: 'Sinta Permata',
    userDivision: 'Warehouse',
    userArea: 'West',
    userRegional: 'Jabar 2',
    courseId: 'c4',
    courseTitle: 'Service Excellence Culture',
    progress: 60,
    status: 'In Progress',
    quizScore: null,
    learningHours: 6.5,
    deadline: '2026-06-20',
  },

  // Dedi (Management, Bandung)
  {
    id: 'e4_1',
    userId: 'u4',
    userName: 'Dedi Kurniawan',
    userDivision: 'Management',
    userArea: 'West',
    userRegional: 'Jabar 2',
    courseId: 'c2',
    courseTitle: 'Transformational Leadership',
    progress: 100,
    status: 'Completed',
    quizScore: 95,
    learningHours: 18.0,
    deadline: '2026-05-15',
  },
  {
    id: 'e4_2',
    userId: 'u4',
    userName: 'Dedi Kurniawan',
    userDivision: 'Management',
    userArea: 'West',
    userRegional: 'Jabar 2',
    courseId: 'c4',
    courseTitle: 'Service Excellence Culture',
    progress: 100,
    status: 'Completed',
    quizScore: 90,
    learningHours: 10.5,
    deadline: '2026-04-30',
  },
  {
    id: 'e4_3',
    userId: 'u4',
    userName: 'Dedi Kurniawan',
    userDivision: 'Management',
    userArea: 'West',
    userRegional: 'Jabar 2',
    courseId: 'c1',
    courseTitle: 'Food Safety Level 1',
    progress: 100,
    status: 'Completed',
    quizScore: 100,
    learningHours: 16.8,
    deadline: '2026-05-20',
  },

  // Citra (Kitchen, Garut)
  {
    id: 'e5_1',
    userId: 'u5',
    userName: 'Citra Dewi',
    userDivision: 'Kitchen',
    userArea: 'West',
    userRegional: 'Jabar 1',
    courseId: 'c1',
    courseTitle: 'Food Safety Level 1',
    progress: 75,
    status: 'In Progress',
    quizScore: null,
    learningHours: 6.0,
    deadline: '2026-06-12',
  },
  {
    id: 'e5_2',
    userId: 'u5',
    userName: 'Citra Dewi',
    userDivision: 'Kitchen',
    userArea: 'West',
    userRegional: 'Jabar 1',
    courseId: 'c3',
    courseTitle: 'SOP Kitchen & Sanitation',
    progress: 20,
    status: 'In Progress',
    quizScore: null,
    learningHours: 2.5,
    deadline: '2026-06-28',
  },

  // Guntur (Kitchen, Bandung)
  {
    id: 'e8_1',
    userId: 'u8',
    userName: 'Guntur Wibowo',
    userDivision: 'Kitchen',
    userArea: 'West',
    userRegional: 'Jabar 2',
    courseId: 'c1',
    courseTitle: 'Food Safety Level 1',
    progress: 100,
    status: 'Completed',
    quizScore: 94,
    learningHours: 11.2,
    deadline: '2026-05-01',
  },
  {
    id: 'e8_2',
    userId: 'u8',
    userName: 'Guntur Wibowo',
    userDivision: 'Kitchen',
    userArea: 'West',
    userRegional: 'Jabar 2',
    courseId: 'c3',
    courseTitle: 'SOP Kitchen & Sanitation',
    progress: 100,
    status: 'Completed',
    quizScore: 92,
    learningHours: 15.5,
    deadline: '2026-05-15',
  },
  {
    id: 'e8_3',
    userId: 'u8',
    userName: 'Guntur Wibowo',
    userDivision: 'Kitchen',
    userArea: 'West',
    userRegional: 'Jabar 2',
    courseId: 'c2',
    courseTitle: 'Transformational Leadership',
    progress: 85,
    status: 'In Progress',
    quizScore: null,
    learningHours: 25.4,
    deadline: '2026-06-18',
  },

  // Hendra (Service, Garut) - Hendra has low progress: 15% In Progress
  {
    id: 'e9_1',
    userId: 'u9',
    userName: 'Hendra Saputra',
    userDivision: 'Service',
    userArea: 'West',
    userRegional: 'Jabar 1',
    courseId: 'c4',
    courseTitle: 'Service Excellence Culture',
    progress: 15,
    status: 'In Progress',
    quizScore: null,
    learningHours: 5.2,
    deadline: '2026-06-14',
  },

  // Indah (Management, Malang)
  {
    id: 'e10_1',
    userId: 'u10',
    userName: 'Indah Putri',
    userDivision: 'Management',
    userArea: 'East',
    userRegional: 'Jatim 1',
    courseId: 'c2',
    courseTitle: 'Transformational Leadership',
    progress: 100,
    status: 'Completed',
    quizScore: 98,
    learningHours: 20.4,
    deadline: '2026-05-15',
  },
  {
    id: 'e10_2',
    userId: 'u10',
    userName: 'Indah Putri',
    userDivision: 'Management',
    userArea: 'East',
    userRegional: 'Jatim 1',
    courseId: 'c4',
    courseTitle: 'Service Excellence Culture',
    progress: 100,
    status: 'Completed',
    quizScore: 92,
    learningHours: 15.4,
    deadline: '2026-05-20',
  },

  // Kiki (Service, Bandung)
  {
    id: 'e12_1',
    userId: 'u12',
    userName: 'Kiki Amelia',
    userDivision: 'Service',
    userArea: 'West',
    userRegional: 'Jabar 2',
    courseId: 'c4',
    courseTitle: 'Service Excellence Culture',
    progress: 10,
    status: 'In Progress',
    quizScore: null,
    learningHours: 2.1,
    deadline: '2026-06-25',
  },

  // Lukman (Kitchen, Malang) - Lukman has overdue training: 0% and deadline has passed
  {
    id: 'e13_1',
    userId: 'u13',
    userName: 'Lukman Hakim',
    userDivision: 'Kitchen',
    userArea: 'East',
    userRegional: 'Jatim 1',
    courseId: 'c3',
    courseTitle: 'SOP Kitchen & Sanitation',
    progress: 5,
    status: 'Overdue',
    quizScore: null,
    learningHours: 19.8,
    deadline: '2026-06-02', // Overdue
  }
];

// Activity timelines
export const mockActivities: Activity[] = [
  {
    id: 'act1',
    userName: 'Budi Santoso',
    userDivision: 'Service',
    type: 'login',
    detail: 'Login ke dalam sistem LMS via Handphone.',
    timestamp: '2026-06-10T09:15:00Z',
  },
  {
    id: 'act2',
    userName: 'Andi Wijaya',
    userDivision: 'Kitchen',
    type: 'quiz_finished',
    detail: 'Menyelesaikan Quiz Food Safety Level 1 dengan nilai sempurna 92.',
    timestamp: '2026-06-10T08:45:00Z',
  },
  {
    id: 'act3',
    userName: 'Dedi Kurniawan',
    userDivision: 'Management',
    type: 'cert_issued',
    detail: 'Sertifikat diterbitkan untuk course "Transformational Leadership".',
    timestamp: '2026-06-10T07:12:00Z',
  },
  {
    id: 'act4',
    userName: 'Indah Putri',
    userDivision: 'Management',
    type: 'course_completed',
    detail: 'Menyelesaikan modul akhir Service Excellence Culture.',
    timestamp: '2026-06-09T16:30:00Z',
  },
  {
    id: 'act5',
    userName: 'System Admin',
    userDivision: 'Management',
    type: 'course_published',
    detail: 'Bahan ajar baru "Digital Marketing for Store Managers" telah dipublikasikan.',
    timestamp: '2026-06-08T09:00:00Z',
  }
];

// Pre-test, Post-test & Learning Gain Index (LGI)
export const mockPrePostTests: PrePostTest[] = [
  {
    id: 'p1',
    userName: 'Andi Wijaya',
    className: 'Kitchen Safety Level 1 - Malang',
    preTest: 60,
    postTest: 90, // LGI +30
  },
  {
    id: 'p2',
    userName: 'Budi Santoso',
    className: 'Leadership Essentials - Garut',
    preTest: 70,
    postTest: 85, // LGI +15
  },
  {
    id: 'p3',
    userName: 'Sinta Permata',
    className: 'Store Operations - Bandung',
    preTest: 50,
    postTest: 80, // LGI +30
  },
  {
    id: 'p4',
    userName: 'Citra Dewi',
    className: 'Kitchen Safety Level 1 - Garut',
    preTest: 45,
    postTest: 88, // LGI +43
  },
  {
    id: 'p5',
    userName: 'Guntur Wibowo',
    className: 'Kitchen Safety Level 1 - Bandung',
    preTest: 68,
    postTest: 94, // LGI +26
  },
  {
    id: 'p6',
    userName: 'Hendra Saputra',
    className: 'Customer Service Culture - Garut',
    preTest: 55,
    postTest: 78, // LGI +23
  },
  {
    id: 'p7',
    userName: 'Indah Putri',
    className: 'Leadership Essentials - Malang',
    preTest: 65,
    postTest: 98, // LGI +33
  },
  {
    id: 'p8',
    userName: 'Kiki Amelia',
    className: 'Customer Service Culture - Bandung',
    preTest: 40,
    postTest: 75, // LGI +35
  }
];

// Feedback rating aspects for Trainer Evaluation
export const mockFeedbackAspects: FeedbackAspect[] = [
  { aspect: 'Penguasaan Materi', score: 4.8 },
  { aspect: 'Komunikasi', score: 4.7 },
  { aspect: 'Interaksi', score: 4.9 },
  { aspect: 'Time Management', score: 4.6 },
  { aspect: 'Kejelasan Penyampaian', score: 4.5 },
  { aspect: 'Pertanyaan & Jawaban', score: 4.7 },
  { aspect: 'Kepuasan Keseluruhan', score: 4.8 },
];

// Qualitative reviews for Trainer Feedback
export const mockFeedbackComments: FeedbackComment[] = [
  {
    id: 'fc1',
    userName: 'Andi Wijaya',
    courseTitle: 'SOP Kitchen & Sanitation',
    comment: 'Trainer sangat menguasai detail prosedur sanitasi dapur standar industri. Penyampaian interaktif dan tidak membosankan.',
    rating: 5,
    timestamp: '2026-06-09T15:20:00Z',
  },
  {
    id: 'fc2',
    userName: 'Budi Santoso',
    courseTitle: 'Transformational Leadership',
    comment: 'Materi leadership dibawakan dengan contoh kasus nyata yang sangat relevan untuk operasional cabang harian.',
    rating: 5,
    timestamp: '2026-06-08T11:45:00Z',
  },
  {
    id: 'fc3',
    userName: 'Sinta Permata',
    courseTitle: 'Service Excellence Culture',
    comment: 'Penyampaian jelas dan ramah. Pengelolaan waktunya sangat bagus sehingga sesi diskusi bisa berjalan teratur.',
    rating: 4,
    timestamp: '2026-06-07T14:30:00Z',
  },
  {
    id: 'fc4',
    userName: 'Dedi Kurniawan',
    courseTitle: 'Transformational Leadership',
    comment: 'Sangat bermanfaat terutama tips memotivasi anggota tim yang sedang underperform. Recomended trainer!',
    rating: 5,
    timestamp: '2026-06-05T10:10:00Z',
  }
];

// Metrics helper logic to emulate database aggregates during testing
export const getActiveUsersHourly = [
  { name: '08:00', Malang: 12, Garut: 8, Bandung: 15 },
  { name: '10:00', Malang: 28, Garut: 19, Bandung: 24 },
  { name: '12:00', Malang: 15, Garut: 12, Bandung: 18 },
  { name: '14:00', Malang: 30, Garut: 25, Bandung: 35 },
  { name: '16:00', Malang: 22, Garut: 18, Bandung: 20 },
  { name: '18:00', Malang: 14, Garut: 10, Bandung: 12 },
  { name: '20:00', Malang: 8, Garut: 6, Bandung: 9 },
];

export const getActiveUsersWeekly = [
  { name: 'Minggu 1', Malang: 110, Garut: 85, Bandung: 120 },
  { name: 'Minggu 2', Malang: 135, Garut: 95, Bandung: 145 },
  { name: 'Minggu 3', Malang: 142, Garut: 112, Bandung: 151 },
  { name: 'Minggu 4', Malang: 168, Garut: 125, Bandung: 172 },
];

export const getActiveUsersMonthly = [
  { name: 'Januari', Malang: 320, Garut: 260, Bandung: 390 },
  { name: 'Februari', Malang: 410, Garut: 310, Bandung: 420 },
  { name: 'Maret', Malang: 480, Garut: 410, Bandung: 510 },
  { name: 'April', Malang: 520, Garut: 450, Bandung: 590 },
  { name: 'Mei', Malang: 610, Garut: 520, Bandung: 670 },
  { name: 'Juni', Malang: 645, Garut: 540, Bandung: 680 },
];

// Course completions count trend data
export const getCompletionsMonthly = [
  { name: 'Januari', Selesai: 18 },
  { name: 'Februari', Selesai: 32 },
  { name: 'Maret', Selesai: 48 },
  { name: 'April', Selesai: 64 },
  { name: 'Mei', Selesai: 79 },
  { name: 'Juni', Selesai: 85 },
];

// Daily logins Bar Chart trend
export const getDailyLogins = [
  { date: 'Senin', logins: 34, status: 'Biasa' },
  { date: 'Selasa', logins: 45, status: 'Biasa' },
  { date: 'Rabu', logins: 78, status: 'Peak' }, // Peak activity
  { date: 'Kamis', logins: 52, status: 'Biasa' },
  { date: 'Jumat', logins: 61, status: 'Biasa' },
  { date: 'Sabtu', logins: 22, status: 'Biasa' },
  { date: 'Minggu', logins: 8, status: 'Sepi' }, // Hari paling sepi
];
